### ISSUE TITLE
Accelorometer data logging

### ISSUE THREAD

**Issue by JBmiog** [HesselM/IN4254-SmartPhoneSensing#6]
For the deadline of may 7th, we need to be able to know if the phone holder is walking or queuing. I propose to make an app to gather data from the accelerometer needed to classify what the phone holder is doing. This app will only be used to log this data.

**Comment by JBmiog** [comment]
Is available on branch " Accelerometer_Logging". Logfile's can be created by imitating walking, queuing, or resting (phone isn't moving). You should set the corresponding button (walking, queuing or resting) to show what type of action you are imitating (Easier for analysing the data).

**Comment by HesselM** [comment]
Closed: code and functions incorporated in branch [activity_monitoring](https://github.com/HesselM/IN4254-SmartPhoneSensing/tree/activity_monitoring).
